### ISSUE TITLE
Image.rb Attributes

### ISSUE THREAD

**Issue by richpeck** [tomharvey/pwinty3-rb#3]
**Added here because didn't want to pollute PR line**
--
I downloaded your gem and loaded it locally.

I didn't change any of my code (apart from several small issues) and the following error showed.

My code can be found [here](https://github.com/richpeck/pwinty-integration/blob/master/app/models/order.rb#L121).

![attributes_err](https://user-images.githubusercontent.com/1104431/72878080-3197b700-3cf2-11ea-910b-8f244b8e4a93.png)

This was caused by the `attributes` hash in [`image.rb`](https://github.com/tomharvey/pwinty3-rb/blob/master/lib/pwinty/image.rb#L15), which is why I commented it out in my other commits.

I will experiment with the `attribute?` method and see if I can create a workable solution.

My stack trace is as follows:

```2020-01-22 08:15:18 - Dry::Struct::Error - [Pwinty::Image.new] {} (Hash) has invalid type for :attributes violates constraints (:substrateWeight is missing in Hash input failed):
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-struct-1.2.0/lib/dry/struct/class_interface.rb:234:in `rescue in new'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-struct-1.2.0/lib/dry/struct/class_interface.rb:225:in `new'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-struct-1.2.0/lib/dry/struct/class_interface.rb:251:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/array/member.rb:34:in `block in call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/array/member.rb:33:in `each'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/array/member.rb:33:in `each_with_object'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/array/member.rb:33:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/constrained.rb:41:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/schema/key.rb:49:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/schema.rb:315:in `block in resolve_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/schema.rb:309:in `each'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/schema.rb:309:in `resolve_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/schema.rb:62:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-types-1.2.2/lib/dry/types/constructor.rb:59:in `call_unsafe'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/dry-struct-1.2.0/lib/dry/struct/class_interface.rb:231:in `new'
08:15:18 web.1  |       c:/Dev/Apps/pwinty3-rb/lib/pwinty.rb:58:in `block in collate_results'
08:15:18 web.1  |       c:/Dev/Apps/pwinty3-rb/lib/pwinty.rb:57:in `each'
08:15:18 web.1  |       c:/Dev/Apps/pwinty3-rb/lib/pwinty.rb:57:in `collate_results'
08:15:18 web.1  |       c:/Dev/Apps/pwinty3-rb/lib/pwinty/order.rb:41:in `list'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/app/models/concerns/import.rb:28:in `import'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/app/app.rb:244:in `block (3 levels) in <class:App>'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/shopify-sinatra-app-0.8.0/lib/sinatra/shopify-sinatra-app.rb:42:in `shopify_session'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/app/app.rb:240:in `block (2 levels) in <class:App>'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:277:in `context'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:271:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/method_override.rb:24:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:277:in `context'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/session/abstract/id.rb:271:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/null_logger.rb:11:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/head.rb:14:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
08:15:18 web.1  |       c:/Dev/Apps/pwinty-integration/.bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'```

**Comment by richpeck** [comment]
I managed to create a fix by referencing the following documentation:
https://dry-rb.org/gems/dry-types/1.0/hash-schemas/#optional-keys

It seems that [`attribute?`](https://dry-rb.org/gems/dry-struct/1.0/recipes/#tolerance-to-missing-keys) has some issues regarding the struct values:
`In the example above nil violates the type constraint so be careful with attribute?.`

I therefore opted to use the optional keys of the hash object. This way, the Hash structure is maintained, whilst providing the ability to have optional attributes.

```
attribute :attributes, Types::Hash.schema(
  substrateWeight?: Types::String,
  frame?: Types::String,
  edge?: Types::String,
  paperType?: Types::String,
  frameColour?: Types::String,
) 
```

I've updated [my gem](https://github.com/richpeck/pwinty3-rb/blob/master/lib/pwinty/image.rb#L15) to accommodate.

**Comment by tomharvey** [comment]
Thanks @richpeck ill have a look into this over the weekend.

**Comment by tomharvey** [comment]
Fixed in PR https://github.com/tomharvey/pwinty3-rb/pull/4

See that for fuller explanation.

**Comment by tomharvey** [comment]
Please re-open if you're still getting this issue.

**Comment by tomharvey** [comment]
v3.0.3 has now been released https://rubygems.org/dashboard

`gem 'pwinty', '>= 3.0.3'`
